void temp()
{
//=========Macro generated from canvas: c1/c1
//=========  (Mon Feb 12 12:29:27 2018) by ROOT version6.06/06
   TCanvas *c1 = new TCanvas("c1", "c1",10,45,700,502);
   gStyle->SetOptStat(0);
   c1->Range(-0.3125,-323.2688,2.8125,2909.419);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   Double_t xAxis1[7] = {0, 0.18, 0.3, 0.45, 0.77, 1.28, 2.5}; 
   
   TH1D *h_eff_mumom_den__1 = new TH1D("h_eff_mumom_den__1","",6, xAxis1);
   h_eff_mumom_den__1->SetBinContent(1,558);
   h_eff_mumom_den__1->SetBinContent(2,1135);
   h_eff_mumom_den__1->SetBinContent(3,1458);
   h_eff_mumom_den__1->SetBinContent(4,2463);
   h_eff_mumom_den__1->SetBinContent(5,1873);
   h_eff_mumom_den__1->SetBinContent(6,650);
   h_eff_mumom_den__1->SetBinContent(7,113);
   h_eff_mumom_den__1->SetEntries(8250);
   h_eff_mumom_den__1->SetStats(0);
   h_eff_mumom_den__1->SetFillColor(30);
   h_eff_mumom_den__1->SetLineColor(30);
   h_eff_mumom_den__1->SetLineWidth(3);
   h_eff_mumom_den__1->GetXaxis()->SetTitle("p_{#mu}^{truth} [GeV]");
   h_eff_mumom_den__1->GetXaxis()->SetNdivisions(506);
   h_eff_mumom_den__1->GetXaxis()->SetLabelFont(42);
   h_eff_mumom_den__1->GetXaxis()->SetTitleSize(0.055);
   h_eff_mumom_den__1->GetXaxis()->SetTitleOffset(0.8);
   h_eff_mumom_den__1->GetXaxis()->SetTitleFont(42);
   h_eff_mumom_den__1->GetYaxis()->SetTitle("Events");
   h_eff_mumom_den__1->GetYaxis()->SetNdivisions(506);
   h_eff_mumom_den__1->GetYaxis()->SetLabelFont(42);
   h_eff_mumom_den__1->GetYaxis()->SetTitleSize(0.055);
   h_eff_mumom_den__1->GetYaxis()->SetTitleOffset(0.9);
   h_eff_mumom_den__1->GetYaxis()->SetTitleFont(42);
   h_eff_mumom_den__1->GetZaxis()->SetNdivisions(506);
   h_eff_mumom_den__1->GetZaxis()->SetLabelFont(42);
   h_eff_mumom_den__1->GetZaxis()->SetTitleSize(0.055);
   h_eff_mumom_den__1->GetZaxis()->SetTitleOffset(0.8);
   h_eff_mumom_den__1->GetZaxis()->SetTitleFont(42);
   h_eff_mumom_den__1->Draw("histo");
   Double_t xAxis2[7] = {0, 0.18, 0.3, 0.45, 0.77, 1.28, 2.5}; 
   
   TH1D *h_eff_mumom_num__2 = new TH1D("h_eff_mumom_num__2","h_eff_mumom_num",6, xAxis2);
   h_eff_mumom_num__2->SetBinContent(1,147);
   h_eff_mumom_num__2->SetBinContent(2,565);
   h_eff_mumom_num__2->SetBinContent(3,856);
   h_eff_mumom_num__2->SetBinContent(4,1451);
   h_eff_mumom_num__2->SetBinContent(5,1107);
   h_eff_mumom_num__2->SetBinContent(6,370);
   h_eff_mumom_num__2->SetBinContent(7,66);
   h_eff_mumom_num__2->SetEntries(4562);
   h_eff_mumom_num__2->SetStats(0);
   h_eff_mumom_num__2->SetFillColor(9);
   h_eff_mumom_num__2->SetLineColor(9);
   h_eff_mumom_num__2->SetLineWidth(3);
   h_eff_mumom_num__2->GetXaxis()->SetNdivisions(506);
   h_eff_mumom_num__2->GetXaxis()->SetLabelFont(42);
   h_eff_mumom_num__2->GetXaxis()->SetTitleSize(0.055);
   h_eff_mumom_num__2->GetXaxis()->SetTitleOffset(0.8);
   h_eff_mumom_num__2->GetXaxis()->SetTitleFont(42);
   h_eff_mumom_num__2->GetYaxis()->SetNdivisions(506);
   h_eff_mumom_num__2->GetYaxis()->SetLabelFont(42);
   h_eff_mumom_num__2->GetYaxis()->SetTitleSize(0.055);
   h_eff_mumom_num__2->GetYaxis()->SetTitleOffset(0.9);
   h_eff_mumom_num__2->GetYaxis()->SetTitleFont(42);
   h_eff_mumom_num__2->GetZaxis()->SetNdivisions(506);
   h_eff_mumom_num__2->GetZaxis()->SetLabelFont(42);
   h_eff_mumom_num__2->GetZaxis()->SetTitleSize(0.055);
   h_eff_mumom_num__2->GetZaxis()->SetTitleOffset(0.8);
   h_eff_mumom_num__2->GetZaxis()->SetTitleFont(42);
   h_eff_mumom_num__2->Draw("histo same");
   
   TLegend *leg = new TLegend(0.5401146,0.7473684,0.8782235,0.8631579,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_eff_mumom_den","Generated #nu_{#mu} CC in FV","l");
   entry->SetLineColor(30);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_eff_mumom_num","Selected #nu_{#mu} CC in FV","l");
   entry->SetLineColor(9);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
